version: "3.9"
services:
  ranking-db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    image: ranking-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - ranking-db
    env_file:
      - .env

#  rabbitmq:
#    image: rabbitmq:3.9-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#
#  celery:
#    build: .
#    command: celery -A app_store_ranking_v2 worker -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - rabbitmq
#    env_file:
#      - .env
