# Generated by Django 4.0.7 on 2022-08-14 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=500)),
                ('session_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], default='not_started', max_length=32)),
                ('type', models.CharField(max_length=32, null=True)),
                ('details', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyApp',
            fields=[
                ('app_handle', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('developed_by', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(default=0)),
                ('app_handle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_rank.session')),
            ],
        ),
        migrations.CreateModel(
            name='RankDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_rank', models.FloatField()),
                ('new_rank', models.FloatField()),
                ('rank_delta', models.FloatField(default=0.0)),
                ('has_app_data_changed', models.BooleanField(default=False)),
                ('extras', models.JSONField(default=dict)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_rank.session')),
                ('shopify_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rank.shopifyapp')),
            ],
        ),
        migrations.CreateModel(
            name='AppRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rank.keyword')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_rank.session')),
                ('shopify_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rank.shopifyapp')),
            ],
        ),
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('signifiers', models.JSONField(default=dict)),
                ('categories', models.JSONField(default=list)),
                ('pricing', models.JSONField(default=dict)),
                ('extras', models.JSONField(default=dict)),
                ('hash', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('shopify_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rank.shopifyapp')),
            ],
        ),
    ]
