# Generated by Django 4.0.7 on 2022-08-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rank', '0002_rankdelta_rank_delta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('session', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_rank.session')),
            ],
        ),
    ]
