# Generated by Django 4.0.7 on 2022-08-09 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_rank', '0003_errorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_id',
            new_name='session_uuid',
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 9, 31, 58, 26438, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
