# Generated by Django 4.0.7 on 2022-08-09 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_rank', '0004_rename_session_id_session_session_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 10, 55, 16, 344953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankdelta',
            name='has_app_data_changed',
            field=models.BooleanField(default=''),
        ),
    ]
