# Generated by Django 4.0.7 on 2022-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rank', '0007_alter_keyword_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='session',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapedhtml',
            name='app_handle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
